pipeline:
  build:
    image: klakegg/hugo:latest
    commands:
      - hugo

  deploy:
    image: alpine/git
    environment:
      - GIT_AUTHOR_NAME=CI
      - GIT_AUTHOR_EMAIL=ci@codeberg.org
    commands:
      - cd public
      - git init
      - git checkout -b pages
      - git add .
      - git commit -m "Deploy site"
      - git remote add origin https://oauth2:${CI_TOKEN}@codeberg.org/detox-24/sathiya.git
      - git push --force origin pages
